from basegrid.basegrid import BaseGrid
from grid.grid import Grid

if __name__ == '__main__':
    bg = BaseGrid()
    bg.get_input()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
    bg.grid.create_next_generation()
    print(bg.grid.grid)
